include: package:flutter_lints/rules.yaml

linter:
  rules:
    - prefer_const_constructors  # Ajuda muito na performance do Flutter
    - always_declare_return_types
    - avoid_print                # Evita que logs de debug cheguem em produção